import { User, Resource, Booking, Review, Message, Notification } from "../types";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@university.edu",
    name: "Admin User",
    role: "admin",
    department: "IT Services",
    profileImage: "https://images.unsplash.com/photo-1576558656222-ba66febe3dec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBoZWFkc2hvdCUyMHBvcnRyYWl0fGVufDF8fHx8MTc2MjgyNDc0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    email: "staff@university.edu",
    name: "Dr. Sarah Johnson",
    role: "staff",
    department: "Computer Science",
    profileImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MXx8fHwxNzYyNzczMTU4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    email: "student@university.edu",
    name: "Alex Martinez",
    role: "student",
    department: "Engineering",
    profileImage: "https://images.unsplash.com/photo-1729697967428-5b98d11486a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWxlJTIwc3R1ZGVudCUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjg4Mzg1OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    createdAt: new Date("2024-09-01"),
  },
  {
    id: "4",
    email: "john.doe@university.edu",
    name: "John Doe",
    role: "student",
    department: "Business",
    profileImage: "https://images.unsplash.com/photo-1672685667592-0392f458f46f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBtYW4lMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjI4MjQ0OTd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    createdAt: new Date("2024-09-01"),
  },
];

// Mock Resources
export const mockResources: Resource[] = [
  {
    id: "r1",
    title: "Innovation Lab Study Room A",
    description: "Modern study room with whiteboard, comfortable seating, and natural lighting. Perfect for group study sessions and project collaboration. Equipped with power outlets and high-speed WiFi.",
    images: ["https://images.unsplash.com/photo-1643199032520-99230e970fb9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1bml2ZXJzaXR5JTIwc3R1ZHklMjByb29tfGVufDF8fHx8MTc2MjgyNjQxMHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"],
    category: "study-room",
    location: "Library Building, 3rd Floor",
    capacity: 6,
    status: "published",
    ownerId: "2",
    ownerName: "Dr. Sarah Johnson",
    equipment: ["Whiteboard", "Projector", "6 Chairs", "Large Table"],
    availabilityRules: "Mon-Fri 8AM-10PM, Sat-Sun 10AM-8PM",
    requiresApproval: false,
    rating: 4.8,
    reviewCount: 24,
    bookingCount: 156,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-11-01"),
  },
  {
    id: "r2",
    title: "Engineering Lab - 3D Printer Station",
    description: "Advanced 3D printing equipment available for engineering and design projects. Includes Prusa i3 MK3S+ printer with various filament options. Training required before first use.",
    images: ["https://images.unsplash.com/photo-1627704671340-0969d7dbac25?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYW1wdXMlMjBsYWJvcmF0b3J5JTIwZXF1aXBtZW50fGVufDF8fHx8MTc2MjgyNjQxMHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"],
    category: "lab-equipment",
    location: "Engineering Building, Room 201",
    capacity: 2,
    status: "published",
    ownerId: "2",
    ownerName: "Dr. Sarah Johnson",
    equipment: ["Prusa i3 MK3S+", "PLA/ABS Filaments", "Design Software", "Safety Equipment"],
    availabilityRules: "Mon-Fri 9AM-6PM (Staff supervision required)",
    requiresApproval: true,
    rating: 4.9,
    reviewCount: 45,
    bookingCount: 89,
    createdAt: new Date("2024-07-20"),
    updatedAt: new Date("2024-10-28"),
  },
  {
    id: "r3",
    title: "Student Center Event Hall",
    description: "Spacious event venue perfect for student organization meetings, presentations, and social gatherings. Features audio system, projector, and flexible seating arrangements.",
    images: ["https://images.unsplash.com/photo-1761344580244-767bc4e2e8c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsZWN0dXJlJTIwaGFsbCUyMGF1ZGl0b3JpdW18ZW58MXx8fHwxNzYyODI2NDExfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"],
    category: "event-space",
    location: "Student Center, 2nd Floor",
    capacity: 100,
    status: "published",
    ownerId: "1",
    ownerName: "Admin User",
    equipment: ["Audio System", "Projector & Screen", "100 Chairs", "Stage Area", "Microphones"],
    availabilityRules: "Available daily 8AM-11PM with advance booking",
    requiresApproval: true,
    rating: 4.6,
    reviewCount: 32,
    bookingCount: 67,
    createdAt: new Date("2024-06-10"),
    updatedAt: new Date("2024-11-05"),
  },
  {
    id: "r4",
    title: "Professional Camera & Lighting Kit",
    description: "Complete video production setup including 4K camera, LED lights, tripod, and audio equipment. Ideal for student media projects, interviews, and content creation.",
    images: ["https://images.unsplash.com/photo-1625252698782-6f9614445f60?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsaWJyYXJ5JTIwbWVldGluZyUyMHNwYWNlfGVufDF8fHx8MTc2MjgyNjQxMHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"],
    category: "av-equipment",
    location: "Media Lab, Student Center",
    capacity: 1,
    status: "published",
    ownerId: "2",
    ownerName: "Dr. Sarah Johnson",
    equipment: ["Sony A7 III Camera", "LED Light Panel (2x)", "Tripod", "Shotgun Microphone", "SD Cards"],
    availabilityRules: "Check-out for up to 3 days, training required",
    requiresApproval: true,
    rating: 4.7,
    reviewCount: 18,
    bookingCount: 43,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-10-15"),
  },
  {
    id: "r5",
    title: "Math Tutoring with Prof. Williams",
    description: "One-on-one calculus and statistics tutoring sessions. Experienced professor available for exam prep, homework help, and concept clarification.",
    images: ["https://images.unsplash.com/photo-1680226426952-514723cee6b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1bml2ZXJzaXR5JTIwY2FtcHVzJTIwYnVpbGRpbmd8ZW58MXx8fHwxNzYyODE5NDY3fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"],
    category: "tutoring",
    location: "Mathematics Building, Office 305",
    capacity: 1,
    status: "published",
    ownerId: "2",
    ownerName: "Dr. Sarah Johnson",
    equipment: [],
    availabilityRules: "Tuesdays & Thursdays 2PM-5PM",
    requiresApproval: false,
    rating: 5.0,
    reviewCount: 56,
    bookingCount: 234,
    createdAt: new Date("2024-09-01"),
    updatedAt: new Date("2024-11-10"),
  },
  {
    id: "r6",
    title: "Library Meeting Room B",
    description: "Quiet private meeting room perfect for thesis discussions, advisor meetings, or focused group work. Window view and excellent sound insulation.",
    images: ["https://images.unsplash.com/photo-1625252698782-6f9614445f60?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsaWJyYXJ5JTIwbWVldGluZyUyMHNwYWNlfGVufDF8fHx8MTc2MjgyNjQxMHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"],
    category: "study-room",
    location: "Library Building, 2nd Floor",
    capacity: 4,
    status: "published",
    ownerId: "1",
    ownerName: "Admin User",
    equipment: ["Whiteboard", "4 Chairs", "Conference Table"],
    availabilityRules: "Mon-Sun 8AM-11PM",
    requiresApproval: false,
    rating: 4.5,
    reviewCount: 31,
    bookingCount: 178,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-11-08"),
  },
];

// Mock Bookings
export const mockBookings: Booking[] = [
  {
    id: "b1",
    resourceId: "r1",
    resourceTitle: "Innovation Lab Study Room A",
    userId: "3",
    userName: "Alex Martinez",
    startTime: new Date("2025-11-15T14:00:00"),
    endTime: new Date("2025-11-15T16:00:00"),
    status: "approved",
    notes: "Working on group project for CS 401",
    recurrence: "none",
    createdAt: new Date("2025-11-10T10:00:00"),
    updatedAt: new Date("2025-11-10T10:05:00"),
  },
  {
    id: "b2",
    resourceId: "r2",
    resourceTitle: "Engineering Lab - 3D Printer Station",
    userId: "3",
    userName: "Alex Martinez",
    startTime: new Date("2025-11-13T10:00:00"),
    endTime: new Date("2025-11-13T14:00:00"),
    status: "pending",
    notes: "Need to print prototype parts for senior design project",
    recurrence: "none",
    createdAt: new Date("2025-11-11T09:00:00"),
    updatedAt: new Date("2025-11-11T09:00:00"),
  },
  {
    id: "b3",
    resourceId: "r5",
    resourceTitle: "Math Tutoring with Prof. Williams",
    userId: "4",
    userName: "John Doe",
    startTime: new Date("2025-11-12T14:00:00"),
    endTime: new Date("2025-11-12T15:00:00"),
    status: "approved",
    notes: "Help with Calc II midterm prep",
    recurrence: "none",
    createdAt: new Date("2025-11-08T12:00:00"),
    updatedAt: new Date("2025-11-08T12:10:00"),
  },
  {
    id: "b4",
    resourceId: "r3",
    resourceTitle: "Student Center Event Hall",
    userId: "4",
    userName: "John Doe",
    startTime: new Date("2025-11-20T18:00:00"),
    endTime: new Date("2025-11-20T22:00:00"),
    status: "pending",
    notes: "Business Club networking event",
    recurrence: "none",
    createdAt: new Date("2025-11-11T15:00:00"),
    updatedAt: new Date("2025-11-11T15:00:00"),
  },
];

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: "rev1",
    resourceId: "r1",
    userId: "3",
    userName: "Alex Martinez",
    userProfileImage: "https://images.unsplash.com/photo-1729697967428-5b98d11486a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWxlJTIwc3R1ZGVudCUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjg4Mzg1OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    rating: 5,
    comment: "Perfect study space! Clean, quiet, and all the equipment worked great. Will definitely book again.",
    createdAt: new Date("2025-11-05T16:30:00"),
  },
  {
    id: "rev2",
    resourceId: "r1",
    userId: "4",
    userName: "John Doe",
    userProfileImage: "https://images.unsplash.com/photo-1672685667592-0392f458f46f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBtYW4lMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjI4MjQ0OTd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    rating: 4,
    comment: "Great location and setup. Only minor issue was the whiteboard markers were running low.",
    createdAt: new Date("2025-11-03T14:20:00"),
  },
  {
    id: "rev3",
    resourceId: "r2",
    userId: "4",
    userName: "John Doe",
    userProfileImage: "https://images.unsplash.com/photo-1672685667592-0392f458f46f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBtYW4lMjBwb3J0cmFpdHxlbnwxfHx8fDE3NjI4MjQ0OTd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    rating: 5,
    comment: "Amazing equipment and Dr. Johnson was very helpful with setup. Print quality was excellent!",
    createdAt: new Date("2025-10-28T11:15:00"),
  },
  {
    id: "rev4",
    resourceId: "r5",
    userId: "3",
    userName: "Alex Martinez",
    userProfileImage: "https://images.unsplash.com/photo-1729697967428-5b98d11486a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWxlJTIwc3R1ZGVudCUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjg4Mzg1OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    rating: 5,
    comment: "Prof. Williams is incredibly patient and explains concepts clearly. Helped me ace my exam!",
    createdAt: new Date("2025-10-25T17:00:00"),
  },
];

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: "m1",
    threadId: "b2",
    senderId: "2",
    senderName: "Dr. Sarah Johnson",
    senderProfileImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MXx8fHwxNzYyNzczMTU4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    receiverId: "3",
    receiverName: "Alex Martinez",
    receiverProfileImage: "https://images.unsplash.com/photo-1729697967428-5b98d11486a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWxlJTIwc3R1ZGVudCUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjg4Mzg1OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    content: "Hi Alex, I've received your booking request for the 3D printer. Could you please confirm you've completed the safety training?",
    read: true,
    createdAt: new Date("2025-11-11T10:00:00"),
  },
  {
    id: "m2",
    threadId: "b2",
    senderId: "3",
    senderName: "Alex Martinez",
    senderProfileImage: "https://images.unsplash.com/photo-1729697967428-5b98d11486a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWxlJTIwc3R1ZGVudCUyMHBvcnRyYWl0fGVufDF8fHx8MTc2Mjg4Mzg1OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    receiverId: "2",
    receiverName: "Dr. Sarah Johnson",
    receiverProfileImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MXx8fHwxNzYyNzczMTU4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    content: "Yes, I completed the training last month on October 10th. My certification number is ST-2024-0356.",
    read: false,
    createdAt: new Date("2025-11-11T11:30:00"),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: "n1",
    userId: "3",
    type: "booking_confirmed",
    title: "Booking Confirmed",
    message: "Your booking for Innovation Lab Study Room A on Nov 15 at 2:00 PM has been confirmed.",
    read: true,
    link: "/bookings",
    createdAt: new Date("2025-11-10T10:05:00"),
  },
  {
    id: "n2",
    userId: "3",
    type: "booking_pending",
    title: "Booking Pending Approval",
    message: "Your booking for Engineering Lab - 3D Printer Station is pending approval from Dr. Sarah Johnson.",
    read: false,
    link: "/bookings",
    createdAt: new Date("2025-11-11T09:00:00"),
  },
  {
    id: "n3",
    userId: "3",
    type: "new_message",
    title: "New Message",
    message: "Dr. Sarah Johnson sent you a message about your booking.",
    read: true,
    link: "/messages",
    createdAt: new Date("2025-11-11T10:00:00"),
  },
];